### ISSUE TITLE
Getting SyntaxError: invalid syntax issue while executing ali command.

### ISSUE THREAD

**Issue by gbhise** [leonrodenburg/ali-cli#9]
I installed ali CLI using command  **pip install ali-cli**, And after installation when I execute ali command it giving me below error:

root@deployServer:/usr/src# ali
Traceback (most recent call last):
  File "/usr/local/bin/ali", line 7, in <module>
    from ali.cli import safe_cli
  File "/usr/local/lib/python2.7/dist-packages/ali/cli.py", line 9, in <module>
    from ali.commands.mns import mns
  File "/usr/local/lib/python2.7/dist-packages/ali/commands/mns/__init__.py", line 3, in <module>
    from ali.commands.mns.queue import queue
  File "/usr/local/lib/python2.7/dist-packages/ali/commands/mns/queue.py", line 7, in <module>
    from ali.commands.mns.client import MnsClient
  File "/usr/local/lib/python2.7/dist-packages/ali/commands/mns/client.py", line 13
    account_id: str,
              ^
SyntaxError: invalid syntax

Do I need to make any changes during installation.

**Comment by gbhise** [comment]
I got the issue it is due to python version, Ali-cli requires python version 3.6 or above.

After installing the latest python version make sure to install ali-cli with the latest python version.
